name: Build & Release Proton-Clang 13 (Ubuntu 22.04)

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: # WAJIB: Biar bot GitHub bisa bikin Release
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pasang Dependencies & Cross-Compiler
      run: |
        sudo apt update
        # Install alat pancing agar bisa build binary ARM64 di mesin Intel
        sudo apt install -y cmake ninja-build build-essential python3 git \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libncurses5-dev wget

    - name: Clone LLVM Project
      run: |
        git clone https://github.com/llvm/llvm-project.git --depth=1 -b llvmorg-13.0.1
        mkdir -p install

    - name: Konfigurasi CMake (Cross-Compile for Native ARM64)
      run: |
        cd llvm-project
        mkdir build && cd build
        # Setting ini memaksa hasil output Clang menjadi binary AArch64
        cmake -G Ninja ../llvm \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="clang;lld;polly" \
          -DLLVM_TARGETS_TO_BUILD="AArch64;ARM" \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DLLVM_HOST_TRIPLE=aarch64-unknown-linux-gnu \
          -DCLANG_VENDOR="Proton-AArch64-Native" \
          -DCMAKE_INSTALL_PREFIX=../../install \
          -DLLVM_INCLUDE_BENCHMARKS=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_STATIC_LINK_CXX_STDLIB=ON \
          -DCMAKE_C_FLAGS="-Wno-unused-but-set-variable -Wno-error" \
          -DCMAKE_CXX_FLAGS="-Wno-unused-but-set-variable -Wno-error"

    - name: Mulai Kompilasi (Heavy Task)
      run: |
        cd llvm-project/build
        ninja install

    - name: Kompres Hasil Build
      run: |
        # Ambil tanggal buat nama file unik
        TAG_NAME="build-$(date +'%Y.%m.%d-%H%M')"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        tar -czvf proton-clang-13-aarch64.tar.gz install/

    - name: Upload ke Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: proton-clang-bin
        path: proton-clang-13-aarch64.tar.gz

    - name: Create Release & Upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_id }}
        name: Proton-Clang 13 Native AArch64 (Build ${{ github.run_number }})
        body: |
          HASIL BUILD NATIVE ARM64 (AArch64).
          Bisa dijalankan langsung di Termux/PRoot Ubuntu tanpa emulator.
          Fix: -Wunused-but-set-variable
        draft: false
        prerelease: false
        files: |
          proton-clang-13-native-aarch64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
